field: 37c95dc4-4ecb-4b31-bb83-e096f0f8fbb7 # Information Block
fieldLayouts:
  54201fe3-abb4-4b16-8655-2d6002c2906b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f0db7fc-ca44-42a2-8fff-cbf4e5e7e72f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d516ea2f-2811-42f0-9e6f-0730738482a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2beb263e-f5a2-4dc4-8fc7-05b0a359bb20 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c54a87d-343b-4f5f-a134-a84b74713bab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6158b78e-d381-4a67-8d45-71053b64daa9
        userCondition: null
fields:
  2beb263e-f5a2-4dc4-8fc7-05b0a359bb20: # Description
    columnSuffix: xjopvwfj
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Write image description here'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6f0db7fc-ca44-42a2-8fff-cbf4e5e7e72f: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:249bb5e4-b293-446a-8c63-e7753010f50e' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:249bb5e4-b293-446a-8c63-e7753010f50e' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 1
