field: c9b3b20d-4c9e-454a-b9c0-6f6827dcf308 # Festival Dates
fieldLayouts:
  3071b188-ef41-4dae-bb8e-3e157b26e042:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5e97a2d8-8dc9-4fa2-af52-c84143e906df # Festival time
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 581e9474-29ad-4f76-8c94-e62a137090b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2b0efff-a348-427e-91c4-879917a7c1a2 # Time Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19e648ec-0e2b-4057-9e4f-033967b3f59a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 13dc5abb-f4b3-4fd1-80d6-4d7632f1ad86
        userCondition: null
fields:
  5e97a2d8-8dc9-4fa2-af52-c84143e906df: # Festival time
    columnSuffix: ylsmfcsn
    contentColumnType: string(80)
    fieldGroup: null
    handle: festivalTime
    instructions: 'What time does the festival take place?'
    name: 'Festival time'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 20
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: '6PM - 23PM'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b2b0efff-a348-427e-91c4-879917a7c1a2: # Time Info
    columnSuffix: scilpbhl
    contentColumnType: string(120)
    fieldGroup: null
    handle: timeInfo
    instructions: 'Does the festival take place on both days? If only one day, then this can be left out. '
    name: 'Time Info'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'both days'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: time
name: TIME
sortOrder: 2
