fieldLayouts:
  48654d0b-52b8-4cf7-8950-b4c85b54aa8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Theme title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9aa23580-abb9-4ceb-a66b-1b80011e8236
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5148dc6c-5663-46f0-b91e-bfd9b178f8fb # Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af6fd0d1-5272-4e08-b2d3-b36fe93788ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d025c469-fb9a-4479-964c-d3ab09f70cb0 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fee35464-feb4-4323-a127-eda5f89fedc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66f008ac-dec3-4e16-8530-d5b9214b74c7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6c35f5e9-051e-4272-a21d-69303ab5397f # Archive Themes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
