fieldLayouts:
  c444b5be-c7d3-4450-8097-19b3b40a1ccd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4c46cbf-dff8-4b3e-9070-136e540a492e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79f962fa-1244-49a4-9f69-a274e35c986e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f2d5514-e833-4991-a3b4-3a577675ccda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 938d4841-ceff-4136-8f8b-3e69bec08ad0 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 603b6d52-f340-4284-a4b0-53a9a45befec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66d7091c-cb22-4899-b656-d3be927f914c # Title theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2b4cd1a-08f0-4f6f-8a41-571ecc9c6c27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 781744bc-da29-4e3b-a99b-54bd265f50bf # Theme Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6336a60c-73ae-4fb2-a96e-368944d0f350
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 742c5b07-c3ba-485a-9b23-7ba710766241 # Theme Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c5421c0-6ca2-4de3-92bf-90e382f9cc32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5148dc6c-5663-46f0-b91e-bfd9b178f8fb # Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43f8812b-7483-4549-b8a6-9a66d4135695
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 146be423-1abd-4f6e-b2ca-991e6e96f7e0 # season
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 773f0d08-f36d-4f04-9feb-472ab6ba003d
            userCondition: null
            warning: null
            width: 100
        name: theme
        uid: bda747d0-4a3e-4034-8bc5-617bb67ed8a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c9b3b20d-4c9e-454a-b9c0-6f6827dcf308 # Festival Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68c4dccd-c028-47ab-801b-b39603777bc4
            userCondition: null
            warning: null
            width: 100
        name: when
        uid: 308bb011-8531-4649-9fbc-29ec3f3b556b
        userCondition: null
handle: festivalDetails
hasTitleField: true
name: 'Festival details'
section: c7f63c6e-197e-4ce8-9204-f8843d5232cd # Festival details
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
