fieldLayouts:
  c444b5be-c7d3-4450-8097-19b3b40a1ccd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4c46cbf-dff8-4b3e-9070-136e540a492e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d025c469-fb9a-4479-964c-d3ab09f70cb0 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f82b8437-7635-46ca-af05-ad40a241e552
            userCondition: null
            warning: null
            width: 100
        name: theme
        uid: bda747d0-4a3e-4034-8bc5-617bb67ed8a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 436ef1ff-888a-45b6-848f-dcf13c26765e # Workshop Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1145f15-6af8-410e-9b9d-dd7e98209c40
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ca77d0f-209d-47f9-a396-be4094b88e0b # Workshop Days
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2398b9df-d207-4787-a4a5-7e11bd59ea65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbe6f10f-d63e-49cb-b09a-e7a4056c51b3 # Workshop Time 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9725b0fe-2b5d-4c15-889c-f8ae2484f825
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95c1b695-b4fb-431e-8eb0-79bb255a0b1d # date
            instructions: 'When is the next edition date and year? '
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6244d9c2-5be1-4971-a8f5-4789bfe5196b
            userCondition: null
            warning: null
            width: 100
        name: when
        uid: 308bb011-8531-4649-9fbc-29ec3f3b556b
        userCondition: null
handle: festivalDetails
hasTitleField: true
name: 'Festival details'
section: c7f63c6e-197e-4ce8-9204-f8843d5232cd # Festival details
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
