fieldLayouts:
  e51a2899-88d2-4272-8631-bd6122c08582:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df4bce1b-8bfb-4355-b7f3-716f4ddd0371
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d025c469-fb9a-4479-964c-d3ab09f70cb0 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66cfcdf9-7a7e-42c9-b72f-c35e3ff4a526
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8339339-0154-4921-be32-9968afc8c679
        userCondition: null
handle: filmarchive
hasTitleField: true
name: filmarchive
section: ccf55044-b588-4c49-9e14-7c127428607d # filmarchive
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
