fieldLayouts:
  0b7fd7c7-76b9-4ce5-83e4-b6cfe723a214:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b61bf599-71ef-4865-9223-67877164ab0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 543dead8-10a5-4dae-b037-6cb2ae2c6b04
        userCondition: null
handle: filmArchive
hasTitleField: false
name: 'Film Archive'
section: 75c3e5d8-1172-452e-93e7-c4a1bc007ad8 # Film Archive
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
