fieldLayouts:
  efa05cbc-a073-4142-8f10-e587d56ed967:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 79f962fa-1244-49a4-9f69-a274e35c986e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac9086d1-2c2a-4dc7-80eb-10acbbad771a
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Film name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d81f5902-f829-4e21-91a6-035f128f6d27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 938d4841-ceff-4136-8f8b-3e69bec08ad0 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aad1054-cfb5-483a-82cb-4186211d72fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01158648-d04e-4a08-8738-8594ccb5eab2 # Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06a4bbb5-259b-42c1-9ca9-5a9f5765766a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5148dc6c-5663-46f0-b91e-bfd9b178f8fb # Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a26cdf1-43de-4a25-ab86-ca6b1f0a7dd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d025c469-fb9a-4479-964c-d3ab09f70cb0 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 049a4a87-7f14-427a-9bc4-2f957b1d66ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfd90484-8d75-4661-b68e-6edd82a8939c # Runtime
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69611aa2-f30c-44e5-b713-25b0fd2cbe79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc74c7bb-cb6e-49c0-a712-bb139b482965 # crew Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f1b9f29-6708-4820-a4ae-7dd0a813ee31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 368975a4-e5b6-421a-998e-ed3d9a3e5298 # Image Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f53d1dfd-505e-4ca8-8cba-d93f06b4b58c
            userCondition: null
            warning: null
            width: 100
        name: 'Film details'
        uid: d668aad4-4fc2-403c-9656-b5304e576672
        userCondition: null
handle: films
hasTitleField: true
name: Films
section: 07f3f03d-4dfe-47f5-9635-86b9e7ee9eb3 # Films
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
