fieldLayouts:
  b458ac17-0deb-48c1-ba7f-4d003ad03842:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4ef93b6-43ba-43ed-b96a-29c45f3abd63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d025c469-fb9a-4479-964c-d3ab09f70cb0 # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89a12e52-28ee-4f13-bc46-badf4db249f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0e30bac-aa62-4a3c-a9cb-fe2de261bbb0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 37c95dc4-4ecb-4b31-bb83-e096f0f8fbb7 # Information Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83d747f1-9ac2-4c10-b5ce-909bc4aaeed7
            userCondition: null
            warning: null
            width: 100
        name: Requirements
        uid: 3e640912-7904-421c-8ae7-7b33b72cfb01
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 13181b27-bdca-4e23-af9e-6ba7a5023d1f # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
