fieldLayouts:
  b458ac17-0deb-48c1-ba7f-4d003ad03842:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4ef93b6-43ba-43ed-b96a-29c45f3abd63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01158648-d04e-4a08-8738-8594ccb5eab2 # Theme
            instructions: 'This years theme'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 501c1a4e-5d05-4df0-8177-fe0fe8d96c0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd75df1d-d963-427e-95f3-1c16562f075d # Festival Date
            instructions: 'Write down festival date'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782524f1-e65b-4d56-9a15-30187d325d9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e96af37-4fa0-4ddf-b947-2605400c65b7 # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62efd59b-da60-423e-a3fc-061119379aca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2edb808-7c9b-44a9-a2e8-9247304f3cf0 # imageDescription
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84595b99-5e03-4ff5-bd7a-359a21b9f226
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: b0e30bac-aa62-4a3c-a9cb-fe2de261bbb0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 37c95dc4-4ecb-4b31-bb83-e096f0f8fbb7 # Information Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83d747f1-9ac2-4c10-b5ce-909bc4aaeed7
            userCondition: null
            warning: null
            width: 100
        name: Information
        uid: 3e640912-7904-421c-8ae7-7b33b72cfb01
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d92d38a-7f70-452d-8708-267031490990 # Hotspot Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fbf69c5-7e8e-4bd4-8aa2-6606c66261ae
            userCondition: null
            warning: null
            width: 100
        name: Hotspot
        uid: 4f7218a7-fa6a-455d-8028-3dad2c2cf572
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 13181b27-bdca-4e23-af9e-6ba7a5023d1f # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
