fieldLayouts:
  ab7dbc61-29a7-4f82-8b36-42146656f948:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 370eb445-6434-44ed-a3b8-f47ccf19fff4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65552792-35e3-4184-bb7c-2bc16a9de349
        userCondition: null
fs: images
handle: uploads
name: Uploads
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
