columnSuffix: gzolupan
contentColumnType: text
fieldGroup: b0957ce1-6c74-4f5d-b2f1-40e0e2abac03 # Films
handle: description
instructions: 'short movie description for the movie preview block'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'short movie description'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
