columnSuffix: gzolupan
contentColumnType: string(500)
fieldGroup: b0957ce1-6c74-4f5d-b2f1-40e0e2abac03 # Films
handle: description
instructions: 'Short movie description for the movie preview block'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: 125
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
