columnSuffix: fylrwlgl
contentColumnType: text
fieldGroup: 5a1e7c98-42f2-432a-b3e4-0c122b2aa876 # homepage
handle: festivalDate
instructions: 'Write the date of the festival here '
name: 'Festival Date'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '25 sept - 10 dec 2023'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
