columnSuffix: null
contentColumnType: string
fieldGroup: 5a1e7c98-42f2-432a-b3e4-0c122b2aa876 # homepage
handle: hotspotBlock
instructions: null
name: 'Hotspot Block'
searchable: false
settings:
  contentTable: '{{%matrixcontent_hotspotblock}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
