columnSuffix: null
contentColumnType: string
fieldGroup: 2ead9e23-6bdd-43c3-9657-e72cfaca7748 # Common
handle: imageBlock
instructions: 'Add a collection of images'
name: 'Image Block'
searchable: false
settings:
  contentTable: '{{%matrixcontent_imageblock}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
