columnSuffix: null
contentColumnType: string
fieldGroup: 7c64e7ab-11d3-4a59-a2e2-41f4e21cd6be # festival
handle: locationPoint
instructions: null
name: 'Location point'
searchable: false
settings:
  contentTable: '{{%matrixcontent_locationpoint}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
