columnSuffix: smazulfi
contentColumnType: text
fieldGroup: 2ead9e23-6bdd-43c3-9657-e72cfaca7748 # Common
handle: subtitle
instructions: 'Write a subtitle here'
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
