columnSuffix: rkdgcdip
contentColumnType: text
fieldGroup: 2ead9e23-6bdd-43c3-9657-e72cfaca7748 # Common
handle: theme
instructions: 'Theme of the edition the movie was made'
name: Theme
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
