columnSuffix: qrqtmwst
contentColumnType: text
fieldGroup: acb9fa15-9ff6-492b-ba30-e046ff889f52 # participate
handle: workshopWhere
instructions: 'Where does the workshop take place? '
name: 'Workshop Where'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Penta Howest Univeristy'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
