columnSuffix: oungsqlb
contentColumnType: text
fieldGroup: acb9fa15-9ff6-492b-ba30-e046ff889f52 # participate
handle: workshopTime
instructions: 'What time do the workshops take place? '
name: 'Workshop Time '
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'between 14:00-16:00'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
