columnSuffix: qgkbumco
contentColumnType: text
fieldGroup: acb9fa15-9ff6-492b-ba30-e046ff889f52 # participate
handle: workshopDays
instructions: 'Which days do the workshops take place? '
name: 'Workshop Days'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Every Saturday'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
