columnSuffix: tfptixqg
contentColumnType: integer(10)
fieldGroup: b0957ce1-6c74-4f5d-b2f1-40e0e2abac03 # Films
handle: year
instructions: 'The year the movie was made'
name: Year
searchable: false
settings:
  decimals: 0
  defaultValue: 2023
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
