columnSuffix: tfptixqg
contentColumnType: integer(10)
fieldGroup: 2ead9e23-6bdd-43c3-9657-e72cfaca7748 # Common
handle: year
instructions: 'The year the movie was made'
name: Year
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
