dateModified: 1686134312
email:
  fromEmail: lilou.barbier@student.howest.be
  fromName: korterdam
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/img'
    type: craft\fs\Local
    url: '@web/assets/img'
meta:
  __names__:
    2ead9e23-6bdd-43c3-9657-e72cfaca7748: Common # Common
    07f3f03d-4dfe-47f5-9635-86b9e7ee9eb3: Films # Films
    75c3e5d8-1172-452e-93e7-c4a1bc007ad8: 'Film Archive' # Film Archive
    79f962fa-1244-49a4-9f69-a274e35c986e: Image # Image
    177a747e-0316-461e-96d1-4a3ed7f2a387: About # About
    249bb5e4-b293-446a-8c63-e7753010f50e: Uploads # Uploads
    938d4841-ceff-4136-8f8b-3e69bec08ad0: Description # Description
    1535a3de-5390-403d-806b-b9674e214560: Home # Home
    5148dc6c-5663-46f0-b91e-bfd9b178f8fb: Year # Year
    5384b688-826f-48c0-8ddf-b43f7453e254: Participate # Participate
    13181b27-bdca-4e23-af9e-6ba7a5023d1f: Home # Home
    50654ac9-b523-4e34-8181-5184d7734b96: Films # Films
    01158648-d04e-4a08-8738-8594ccb5eab2: Theme # Theme
    3867285b-e2d9-4bf2-813e-38639300f4c4: korterdam # korterdam
    aa1a3e63-bc1f-4863-903d-5bad285c2da6: 'Public Schema' # Public Schema
    b0957ce1-6c74-4f5d-b2f1-40e0e2abac03: Films # Films
    bad43b45-6309-450c-a22e-3f4566433864: 'Film Archive' # Film Archive
    c7f63c6e-197e-4ce8-9204-f8843d5232cd: About # About
    d025c469-fb9a-4479-964c-d3ab09f70cb0: Paragraph # Paragraph
    d95e7483-5ac0-4182-9e02-37b1870fb31b: korterdam # korterdam
    df2b3eb6-296b-42f5-9347-152e42156fcb: filmarchive # filmarchive
    fd8ec98f-11cf-4d4b-a6a6-0cb932a93541: Participate # Participate
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of Korkijk Film Festival'
      prependSubject: 'New message from Korkijk Film Festival'
      successFlashMessage: 'Your message has been sent.'
      toEmail: kristin.erlingsdottir@student.howest.be
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: kristin.erlingsdottir@student.howest.be
      from_name: ''
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '3'
      success_message: 'Thank You for applying to Korkijk Film Festival workshops! '
      volume_id: ''
system:
  edition: pro
  live: true
  name: korterdam
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
