dateModified: 1685558057
email:
  fromEmail: lilou.barbier@student.howest.be
  fromName: kortkijk
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2a135274-a469-4f7e-900e-fc0bc70ed3c3: kortkijk # kortkijk
    3a9d522e-5500-4663-a4d9-162830130a81: Common # Common
    7e186b00-f55c-4b5b-b3bd-e417d6d64350: kortkijk # kortkijk
system:
  edition: solo
  live: true
  name: kortkijk
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
