dateModified: 1685622992
email:
  fromEmail: lilou.barbier@student.howest.be
  fromName: korterdam
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2ead9e23-6bdd-43c3-9657-e72cfaca7748: Common # Common
    1535a3de-5390-403d-806b-b9674e214560: home # home
    13181b27-bdca-4e23-af9e-6ba7a5023d1f: home # home
    3867285b-e2d9-4bf2-813e-38639300f4c4: korterdam # korterdam
    d025c469-fb9a-4479-964c-d3ab09f70cb0: Paragraph # Paragraph
    d95e7483-5ac0-4182-9e02-37b1870fb31b: korterdam # korterdam
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: korterdam
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
