dateModified: 1686763233
email:
  fromEmail: lilou.barbier@student.howest.be
  fromName: korterdam
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/img'
    type: craft\fs\Local
    url: '@web/assets/img'
meta:
  __names__:
    00c08bc0-6c5b-45ba-b369-702d154371c6: 'Extra Title' # Extra Title
    0d92d38a-7f70-452d-8708-267031490990: 'Hotspot Block' # Hotspot Block
    00ee5f40-77e2-4edb-bbe8-0fd66a8c9f92: image # image
    2beb263e-f5a2-4dc4-8fc7-05b0a359bb20: Description # Description
    2ca77d0f-209d-47f9-a396-be4094b88e0b: 'Workshop Days' # Workshop Days
    2ead9e23-6bdd-43c3-9657-e72cfaca7748: Common # Common
    5a1e7c98-42f2-432a-b3e4-0c122b2aa876: homepage # homepage
    6f0db7fc-ca44-42a2-8fff-cbf4e5e7e72f: Image # Image
    7b74703c-5ea3-499a-b922-7bb214e7c7be: 'Info Title' # Info Title
    07f3f03d-4dfe-47f5-9635-86b9e7ee9eb3: Films # Films
    17a90ad1-914f-4548-8a6e-4d916ba366a6: 'Workshop Where' # Workshop Where
    21bc20ed-7930-49c3-9968-7d079e4a1bd3: Paragraph # Paragraph
    25ffa7df-6a7d-4d57-a2cf-953a46b9af82: 'Info Title' # Info Title
    30d647d9-b228-42ed-af39-c82f2ee9b0b1: Year # Year
    37c95dc4-4ecb-4b31-bb83-e096f0f8fbb7: 'Information Block' # Information Block
    38eb2561-b6eb-4380-8c04-6a023e424186: 'Button text ' # Button text 
    66d7091c-cb22-4899-b656-d3be927f914c: 'Theme Long Version' # Theme Long Version
    69e50502-25ac-4c7f-a5ec-17cd4d250086: Image # Image
    75c3e5d8-1172-452e-93e7-c4a1bc007ad8: 'Film Archive' # Film Archive
    79f962fa-1244-49a4-9f69-a274e35c986e: Image # Image
    146be423-1abd-4f6e-b2ca-991e6e96f7e0: season # season
    177a747e-0316-461e-96d1-4a3ed7f2a387: 'Festival details' # Festival details
    249bb5e4-b293-446a-8c63-e7753010f50e: Uploads # Uploads
    436ef1ff-888a-45b6-848f-dcf13c26765e: 'Workshop Date' # Workshop Date
    938d4841-ceff-4136-8f8b-3e69bec08ad0: Description # Description
    1535a3de-5390-403d-806b-b9674e214560: Home # Home
    3424eb75-09d2-417c-95cf-16afc24e0145: Subtitle # Subtitle
    5148dc6c-5663-46f0-b91e-bfd9b178f8fb: Year # Year
    5384b688-826f-48c0-8ddf-b43f7453e254: Participation # Participation
    13181b27-bdca-4e23-af9e-6ba7a5023d1f: Home # Home
    50654ac9-b523-4e34-8181-5184d7734b96: Films # Films
    01158648-d04e-4a08-8738-8594ccb5eab2: Theme # Theme
    3867285b-e2d9-4bf2-813e-38639300f4c4: korterdam # korterdam
    78826962-7de7-4701-b106-29463b46dc72: Subtitle # Subtitle
    a0a5f2ff-3095-45a1-8de0-99499ce5b972: Subtitle # Subtitle
    aa058375-f842-4896-9343-26eab30b8a27: description # description
    aa1a3e63-bc1f-4863-903d-5bad285c2da6: 'Public Schema' # Public Schema
    acb9fa15-9ff6-492b-ba30-e046ff889f52: participate # participate
    b0957ce1-6c74-4f5d-b2f1-40e0e2abac03: Films # Films
    b2b5e0aa-4b38-43e5-82a5-d99ee55a4c83: Image # Image
    b5cfd379-50ac-4af6-9144-d239a9dd6036: 'Info text' # Info text
    bad43b45-6309-450c-a22e-3f4566433864: 'Film Archive' # Film Archive
    bbe6f10f-d63e-49cb-b09a-e7a4056c51b3: 'Workshop Time ' # Workshop Time 
    bd75df1d-d963-427e-95f3-1c16562f075d: 'Festival Date' # Festival Date
    bfc31c34-c1d9-45be-9613-734f6e445e05: Paragraph # Paragraph
    c7f63c6e-197e-4ce8-9204-f8843d5232cd: 'Festival details' # Festival details
    d025c469-fb9a-4479-964c-d3ab09f70cb0: Paragraph # Paragraph
    d6f606d2-4ce4-4f44-b948-c48db769b86a: 'Application State' # Application State
    d95e7483-5ac0-4182-9e02-37b1870fb31b: korterdam # korterdam
    df2b3eb6-296b-42f5-9347-152e42156fcb: filmarchive # filmarchive
    e4c780c9-3b42-4968-a520-733bf5cc84eb: 'Extra Title' # Extra Title
    e4106e18-d069-4cb2-84f6-ac0846bf18c7: infoText # infoText
    fd8ec98f-11cf-4d4b-a6a6-0cb932a93541: Participation # Participation
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of Korkijk Film Festival'
      prependSubject: 'New message from Korkijk Film Festival'
      successFlashMessage: 'Your message has been sent.'
      toEmail: kristin.erlingsdottir@student.howest.be
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: kristin.erlingsdottir@student.howest.be
      from_name: ''
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '3'
      success_message: 'Thank You for applying to Korkijk Film Festival workshops! '
      volume_id: ''
system:
  edition: pro
  live: true
  name: korterdam
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
