defaultPlacement: end
enableVersioning: true
handle: archiveThemes
name: 'Archive Themes'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3867285b-e2d9-4bf2-813e-38639300f4c4: # korterdam
    enabledByDefault: true
    hasUrls: true
    template: _/archiveThemes/_entry
    uriFormat: 'film-archive/{slug}'
type: channel
