defaultPlacement: end
enableVersioning: true
handle: filmArchive
name: 'Film Archive'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3867285b-e2d9-4bf2-813e-38639300f4c4: # korterdam
    enabledByDefault: true
    hasUrls: true
    template: _/pages/filmArchive.twig
    uriFormat: film-archive
type: single
